@startuml
hide empty members

package TestLanguage {

class Child {

+myInt

+myString

+myBool
}

' this class extends:
' this class has interfaces:
Interface <|-- Child 


class Parent {
}

' this class extends:
Ancestor <|-- Parent 
' this class has interfaces:

Parent o-- "0..1"ReferedTo : ref
Parent *-- "0..1" Child : child

interface Interface {
}
hide empty members
' this interface extends:

}
@enduml

