package org.campagnelab.diagrams.generator.ToPlantUmlText;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ISelector;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.generator.template.TemplateQueryContext;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static boolean baseMappingRule_Condition_2103504629858911172(final BaseMappingRuleContext _context) {
    return ListSequence.fromList(SModelOperations.getRoots(_context.getInputModel(), "org.campagnelab.diagrams.structure.HiddenConcepts")).all(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return !(ListSequence.fromList(SLinkOperations.getTargets(it, "hidden", true)).where(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return (SLinkOperations.getTarget(it, "concept", false) != null);
          }
        }).select(new ISelector<SNode, SNode>() {
          public SNode select(SNode it) {
            return SLinkOperations.getTarget(it, "concept", false);
          }
        }).contains(_context.getNode()));
      }
    });
  }

  public static Object propertyMacro_GetPropertyValue_5039633819244230867(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6921256030982451581(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "extends", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_6921256030982247014(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2103504629858709414(final PropertyMacroContext _context) {
    return ((String) _context.getVariable("var:sourceName"));
  }

  public static Object propertyMacro_GetPropertyValue_2103504629858711278(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "target", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_2103504629858727665(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "role");
  }

  public static Object propertyMacro_GetPropertyValue_5039633819244142427(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_9012155033979441221(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_9012155033978774874(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_5039633819242565268(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static boolean ifMacro_Condition_6921256030982536411(final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "extends", false) != null) & !(isEmptyString(ListSequence.fromList(SModelOperations.getRoots(_context.getInputModel(), "org.campagnelab.diagrams.structure.HiddenConcepts")).translate(new ITranslator2<SNode, String>() {
      public Iterable<String> translate(SNode it) {
        return ListSequence.fromList(SLinkOperations.getTargets(it, "hidden", true)).where(new IWhereFilter<SNode>() {
          public boolean accept(SNode it) {
            return (SLinkOperations.getTarget(it, "concept", false) != null);
          }
        }).select(new ISelector<SNode, SNode>() {
          public SNode select(SNode it) {
            return SLinkOperations.getTarget(it, "concept", false);
          }
        }).select(new ISelector<SNode, String>() {
          public String select(SNode it) {
            return SPropertyOperations.getString(it, "name");
          }
        });
      }
    }).findFirst(new IWhereFilter<String>() {
      public boolean accept(String it) {
        return it.equals(SPropertyOperations.getString(_context.getNode(), "name"));
      }
    })));
  }

  public static Iterable<SNode> sourceNodesQuery_5039633819243868119(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "propertyDeclaration", true);
  }

  public static Iterable<SNode> sourceNodesQuery_2103504629858700153(final SourceSubstituteMacroNodesContext _context) {
    if (LOG.isInfoEnabled()) {
      LOG.info("genContext.sourceName" + ((String) _context.getVariable("var:sourceName")));
    }

    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "linkDeclaration", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.hasValue(it, "metaClass", "aggregation", "reference");
      }
    });
  }

  public static Iterable<SNode> sourceNodesQuery_9012155033979532330(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "concepts", true)).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (SLinkOperations.getTarget(it, "concept", false) != null);
      }
    }).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, "concept", false);
      }
    });
  }

  public static Iterable<SNode> sourceNodesQuery_5039633819244250101(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "languages", true);
  }

  public static Iterable<SNode> sourceNodesQuery_5039633819242566104(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "propertyDeclaration", true);
  }

  public static Object insertMacro_varValue_9012155033982222090(final TemplateQueryContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  protected static Logger LOG = LogManager.getLogger(QueriesGenerated.class);

  private static boolean isEmptyString(String str) {
    return str == null || str.length() == 0;
  }
}
