package TestLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Ancestor_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Ancestor_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TestLanguage.structure.Ancestor";
  }
}
