package TestLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Child_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Interface_BehaviorDescriptor {
  public Child_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TestLanguage.structure.Child";
  }
}
