package TestLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Parent_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Parent_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TestLanguage.structure.Parent";
  }
}
