package TestLanguage.behavior;

/*Generated by MPS */


public class Parent_BehaviorDescriptor extends Ancestor_BehaviorDescriptor {
  public Parent_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TestLanguage.structure.Parent";
  }
}
