package TestLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ReferedTo_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ReferedTo_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "TestLanguage.structure.ReferedTo";
  }
}
