@startuml

package org.campagnelab.diagrams {

class LanguageView {
}
LanguageView o-- Language : languages
LanguageView o-- HiddenConcepts : hiddenConcepts

class ConceptReference {
}

class Language {
}
Language o-- ConceptReference : concepts
}
@enduml

