@startuml

package org.campagnelab.diagrams {

class LanguageView {
}
hide empty members
LanguageView *-- "0..n" Language : languages
LanguageView *-- "0..1" HiddenConcepts : hiddenConcepts

class ConceptReference {
}
hide empty members
ConceptReference o-- "1"AbstractConceptDeclaration : concept

class Language {
}
hide empty members
Language *-- "0..n" ConceptReference : concepts
}
@enduml

