package org.campagnelab.diagrams.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class HiddenConcepts_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public HiddenConcepts_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.diagrams.structure.HiddenConcepts";
  }
}
