package org.campagnelab.diagrams.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0b, conceptFqName)) {
      case 0:
        return new ConceptDescriptorBuilder("org.campagnelab.diagrams.structure.ConceptReference").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").references("concept").create();
      case 1:
        return new ConceptDescriptorBuilder("org.campagnelab.diagrams.structure.HiddenConcepts").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept").children(new String[]{"hidden"}, new boolean[]{true}).create();
      case 2:
        return new ConceptDescriptorBuilder("org.campagnelab.diagrams.structure.Language").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").children(new String[]{"concepts"}, new boolean[]{true}).create();
      case 3:
        return new ConceptDescriptorBuilder("org.campagnelab.diagrams.structure.LanguageView").super_("jetbrains.mps.lang.core.structure.BaseConcept").parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").children(new String[]{"languages", "hiddenConcepts"}, new boolean[]{true, false}).alias("Language View", "").create();
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }

  private static String[] stringSwitchCases_1htk8d_a0a0b = new String[]{"org.campagnelab.diagrams.structure.ConceptReference", "org.campagnelab.diagrams.structure.HiddenConcepts", "org.campagnelab.diagrams.structure.Language", "org.campagnelab.diagrams.structure.LanguageView"};
}
